name: Sync with Azure DevOps

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Sync with Azure DevOps
        env:
          AZUREPAT: ${{secrets.AZUREPAT}}
          AZUSERNAME: ${{secrets.AZUSERNAME}}
          AZUSER_EMAIL: ${{secrets.AZUSER_EMAIL}}
          AZORG: ${{secrets.AZORG}}
        run: |
          # Assign the environment variables passed as arguments to variables
          AZUSER_EMAIL=$AZUSER_EMAIL
          AZORG=$AZORG

          # Clone the source repository and remove the Git metadata
          git clone https://github.com/Abdul7777K/test.git
          cd test
          rm -rf .git

          # Clone the target repository using Azure DevOps authentication
          GIT_CMD_REPOSITORY="https://nageshdevops77@outlook.com:5o5kcsg2hhx5heyixa7e6deigrgbgvlwwxx6ckzv52zuooppglea@dev.azure.com/$AZORG/Abdul/_git/syncWithgitEshopCommerce" 
          git clone $GIT_CMD_REPOSITORY

          # Copy the source files to the target repository
          cp -r test/* syncWithgitEshopCommerce/

          cd syncWithgitEshopCommerce

          # Set the Git user name and email
          git config --global user.email "$AZUSER_EMAIL"
          git config --global user.name "nageshdevops77@outlook.com"

          # Commit the changes and push to the target repository
          git add .
          git commit -m "sync from git to azure"
          git push
