name: Push directory to another repository
on: push
jobs:
  check-bats-version:
    runs-on: windows-latest
    environment: AzurePAT
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      env:
        AZUREPAT: ${{secrets.AZUREPAT}}
        AZUSERNAME: ${{secrets.AZUSERNAME}}
        AZUSER_EMAIL: ${{secrets.AZUSER_EMAIL}}
        AZORG: ${{secrets.AZORG}}
      run: |
         Get-Content pwoer.ps1 | Set-Content commit-modified.ps1 -Encoding UTF8
         .\commit-modified.ps1
      shell: powershell
